const categoryItems = [
    {
      title:'Action',
      images:[
        '/src/assets/images/categories/action/1-action.jpg',
        '/src/assets/images/categories/action/2-action.jpg',
        '/src/assets/images/categories/action/3-action.jpg',
        '/src/assets/images/categories/action/4-action.jpg'  
      ]
    },
    {
      title:'Adventure',
      images:[
        '/src/assets/images/categories/adventure/1-adv.jpg',
        '/src/assets/images/categories/adventure/2-adv.jpg',
        '/src/assets/images/categories/adventure/3-adv.jpg',
        '/src/assets/images/categories/adventure/4-adv.jpg'  
      ]
    },
    {
      title:'Comedy',
      images:[
        '/src/assets/images/categories/comedy/1-comedy.jpg',
        '/src/assets/images/categories/comedy/2-comedy.jpg',
        '/src/assets/images/categories/comedy/3-comedy.jpg',
        '/src/assets/images/categories/comedy/4-comedy.jpg'  
      ]
    },
    {
      title:'Drama',
      images:[
        '/src/assets/images/categories/drama/1-drama.jpg',
        '/src/assets/images/categories/drama/2-drama.jpg',
        '/src/assets/images/categories/drama/3-drama.jpg',
        '/src/assets/images/categories/drama/4-drama.jpg'  
      ]
    },
    {
      title:'Horror',
      images:[
        '/src/assets/images/categories/horror/1-horror.jpg',
        '/src/assets/images/categories/horror/2-horror.jpg',
        '/src/assets/images/categories/horror/3-horror.jpg',
        '/src/assets/images/categories/horror/4-horror.jpg'  
      ]
    },
    {
      title:'Action',
      images:[
        '/src/assets/images/categories/action/1-action.jpg',
        '/src/assets/images/categories/action/2-action.jpg',
        '/src/assets/images/categories/action/3-action.jpg',
        '/src/assets/images/categories/action/4-action.jpg'  
      ]
    },
    {
      title:'Adventure',
      images:[
        '/src/assets/images/categories/adventure/1-adv.jpg',
        '/src/assets/images/categories/adventure/2-adv.jpg',
        '/src/assets/images/categories/adventure/3-adv.jpg',
        '/src/assets/images/categories/adventure/4-adv.jpg'  
      ]
    },
    {
      title:'Comedy',
      images:[
        '/src/assets/images/categories/comedy/1-comedy.jpg',
        '/src/assets/images/categories/comedy/2-comedy.jpg',
        '/src/assets/images/categories/comedy/3-comedy.jpg',
        '/src/assets/images/categories/comedy/4-comedy.jpg'  
      ]
    },
    {
      title:'Drama',
      images:[
        '/src/assets/images/categories/drama/1-drama.jpg',
        '/src/assets/images/categories/drama/2-drama.jpg',
        '/src/assets/images/categories/drama/3-drama.jpg',
        '/src/assets/images/categories/drama/4-drama.jpg'  
      ]
    },
    {
      title:'Horror',
      images:[
        '/src/assets/images/categories/horror/1-horror.jpg',
        '/src/assets/images/categories/horror/2-horror.jpg',
        '/src/assets/images/categories/horror/3-horror.jpg',
        '/src/assets/images/categories/horror/4-horror.jpg'  
      ]
    },
    {
      title:'Comedy',
      images:[
        '/src/assets/images/categories/comedy/1-comedy.jpg',
        '/src/assets/images/categories/comedy/2-comedy.jpg',
        '/src/assets/images/categories/comedy/3-comedy.jpg',
        '/src/assets/images/categories/comedy/4-comedy.jpg'  
      ]
    },
    {
      title:'Drama',
      images:[
        '/src/assets/images/categories/drama/1-drama.jpg',
        '/src/assets/images/categories/drama/2-drama.jpg',
        '/src/assets/images/categories/drama/3-drama.jpg',
        '/src/assets/images/categories/drama/4-drama.jpg'  
      ]
    },
    {
      title:'Horror',
      images:[
        '/src/assets/images/categories/horror/1-horror.jpg',
        '/src/assets/images/categories/horror/2-horror.jpg',
        '/src/assets/images/categories/horror/3-horror.jpg',
        '/src/assets/images/categories/horror/4-horror.jpg'  
      ]
    },
    
   
  ]

  export default categoryItems